### ISSUE TITLE
GCC-6.3.0 ptrdiff_t does not name a type

### ISSUE THREAD

**Issue by flgw** [tysonbrochu/eltopo#12]
In file included from main.cpp:44:0:
../common/array2.h:28:4: error: ‘ptrdiff_t’ does not name a type
    ptrdiff_t ni, nj;
    ^~~~~~~~~

**Comment by h00shi** [comment]
This worked for me: I added ```#include <cstddef>``` to common/array2.h .

**Comment by meshmixer** [comment]
I made this change in master. @flgw can you please confirm that it's working now and if so, close this issue?

**Comment by tysonbrochu** [comment]
I made this change in master. @flgw can you please confirm that it's working now and if so, close this issue?
