### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Flameeyes** [tysonbrochu/eltopo#6]
Hello,

I'm a Gentoo Linux developer, and I'm one of the maintainers for Blender. While updating it today, I noted that eltopo is actually bundled in it. I went looking for the original library so that I could package it separately, and since I found that the build system wouldn't be too flexible for distributions, I ended up writing an autotools-based one, that most distributions would be happy to use...

Unfortunately, now I notice that there is no license assigned to any file in this package, which means for us that we have to treat it as an "all rights reserved" proprietary package. Is this intentional, or just an oversight?

Please note that if you want to just have the most open license possible, you still have to declare copyright and a license — I'd strongly suggest going with either the [WTFPL](https://www.gnu.org/licenses/license-list.html#WTFPL) or the [X11/MIT license](https://www.gnu.org/licenses/license-list.html#X11License) (I'm linking to FSF only because they have a note about their actual free/non-free status that most distributions follow ... I'm in no way suggesting you ought to copyleft this as they are, although if you feel that's a good decision, go for it).

Just please handle licensing one way or the other, I'll be glad to contribute back my changes, and the buildsystem, then so that your software can be made available to Gentoo Linux's users, and we'll build Blender against that.

Thanks,
Diego

**Comment by alecjacobson** [comment]
I'd be curious to find out if you ever picked a license for el topo.

**Comment by ideasman42** [comment]
According to http://www.cs.ubc.ca/labs/imager/tr/2009/eltopo/eltopo.html its public domain.
Though it would be good to include a `LICENSE` file in the source repository.

**Comment by christopherbatty** [comment]
FWIW another option is the Los Topos library, which we put explicitly under a FreeBSD license and which has some improved merging functionality, along with support for multiple materials. (I hope Tyson will forgive this shameless plug.)
http://www.cs.columbia.edu/cg/multitracker/code/

**Comment by tysonbrochu** [comment]
Yeah, I always intended it to be public domain, however I now realize that this was a mistake, and we should have chosen a license from the start. I'm not sure if legally I can now apply a license to it or not. At one point we were going to meet with the UBC IP office to see what we could do, but I ended up graduating before we got around to it.

Anyways, I wholeheartedly endorse Los Topos if you need code with a license -- it basically does everything El Topo does and more. Even if you don't care about multimaterial tracking, the improved merging operation is really nice.

**Comment by alecjacobson** [comment]
cool. thanks.
